/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_24;

import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author marti
 */
public class Admin extends javax.swing.JFrame {
private InfDB idb;
private String ePost;


    /**
     * Creates new form Admin
     */
    public Admin(InfDB idb,String ePost) {
        this.idb = idb;
        this.ePost = ePost;
        initComponents();
         lblInloggadAnvandare.setText(ePost);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValkommen = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblInloggadAnvandare = new javax.swing.JLabel();
        tabbedPanel = new javax.swing.JTabbedPane();
        panelAvdelning = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        panelAnstallda = new javax.swing.JPanel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaAvdelning = new javax.swing.JTextArea();
        panelMinInfo = new javax.swing.JPanel();
        btnAndraMinInfo = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        lblLOGGA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValkommen.setText("Välkommen!");

        lblAdmin.setText("Admin");

        lblInloggadAnvandare.setText("inloggadAnvändare");

        jToggleButton2.setText("Ändra avdelning");
        jToggleButton2.setPreferredSize(new java.awt.Dimension(130, 25));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAvdelningLayout = new javax.swing.GroupLayout(panelAvdelning);
        panelAvdelning.setLayout(panelAvdelningLayout);
        panelAvdelningLayout.setHorizontalGroup(
            panelAvdelningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAvdelningLayout.createSequentialGroup()
                .addContainerGap(819, Short.MAX_VALUE)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelAvdelningLayout.setVerticalGroup(
            panelAvdelningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvdelningLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(567, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Avdelning", panelAvdelning);

        panelAnstallda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panelAnstalldaFocusGained(evt);
            }
        });

        jToggleButton3.setText("Ändra anställda");
        jToggleButton3.setPreferredSize(new java.awt.Dimension(130, 25));

        txtAreaAvdelning.setColumns(20);
        txtAreaAvdelning.setRows(5);
        txtAreaAvdelning.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAreaAvdelningFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(txtAreaAvdelning);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAnstalldaLayout = new javax.swing.GroupLayout(panelAnstallda);
        panelAnstallda.setLayout(panelAnstalldaLayout);
        panelAnstalldaLayout.setHorizontalGroup(
            panelAnstalldaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnstalldaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelAnstalldaLayout.setVerticalGroup(
            panelAnstalldaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnstalldaLayout.createSequentialGroup()
                .addGroup(panelAnstalldaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAnstalldaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAnstalldaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Anställda", panelAnstallda);

        btnAndraMinInfo.setText("Ändra min info");
        btnAndraMinInfo.setPreferredSize(new java.awt.Dimension(130, 25));

        javax.swing.GroupLayout panelMinInfoLayout = new javax.swing.GroupLayout(panelMinInfo);
        panelMinInfo.setLayout(panelMinInfoLayout);
        panelMinInfoLayout.setHorizontalGroup(
            panelMinInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMinInfoLayout.createSequentialGroup()
                .addContainerGap(810, Short.MAX_VALUE)
                .addComponent(btnAndraMinInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMinInfoLayout.setVerticalGroup(
            panelMinInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMinInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAndraMinInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(567, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Min info", panelMinInfo);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("tab4", jPanel4);

        lblLOGGA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo_24/SDG+Wheel.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValkommen)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAdmin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblInloggadAnvandare)))
                        .addGap(660, 660, 660)
                        .addComponent(lblLOGGA, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(27, 27, 27)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblValkommen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdmin)
                            .addComponent(lblInloggadAnvandare))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLOGGA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(tabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void panelAnstalldaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelAnstalldaFocusGained
         panelAvdelning.setVisible(true);
        txtAreaAvdelning.setText("");

        ArrayList<HashMap<String,String>> allaAvdelning;

        try {
            String sqlAvdelning = "SELECT * FROM avdelning INNER JOIN anstalld ON avdelning.avdid = anstalld.avdelning WHERE anstalld.ePost = '" + ePost +"'";
            allaAvdelning = idb.fetchRows(sqlAvdelning);

            for(HashMap<String,String> avdelning : allaAvdelning ){
                txtAreaAvdelning.append(avdelning.get("avdid") + "\t");
                txtAreaAvdelning.append(avdelning.get("namn") + "\t");
                txtAreaAvdelning.append(avdelning.get("beskrivning") + "\t");
                txtAreaAvdelning.append(avdelning.get("adress") + "\t");
                txtAreaAvdelning.append(avdelning.get("epost") + "\t");
                txtAreaAvdelning.append(avdelning.get("telefon") + "\t");
                txtAreaAvdelning.append(avdelning.get("stad") + "\t");
                txtAreaAvdelning.append(avdelning.get("chef") + "\t");

            }
        }catch(InfException ex){
            System.out.println(ex.getMessage());

        }

    }//GEN-LAST:event_panelAnstalldaFocusGained

    private void txtAreaAvdelningFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAreaAvdelningFocusGained
        panelAvdelning.setVisible(true);
        txtAreaAvdelning.setText("");

        ArrayList<HashMap<String,String>> allaAvdelning;

        try {
            String sqlAvdelning = "SELECT * FROM avdelning INNER JOIN anstalld ON avdelning.avdid = anstalld.avdelning WHERE anstalld.ePost = '" + ePost +"'";
            allaAvdelning = idb.fetchRows(sqlAvdelning);

            for(HashMap<String,String> avdelning : allaAvdelning ){
                txtAreaAvdelning.append(avdelning.get("avdid") + "\t");
                txtAreaAvdelning.append(avdelning.get("namn") + "\t");
                txtAreaAvdelning.append(avdelning.get("beskrivning") + "\t");
                txtAreaAvdelning.append(avdelning.get("adress") + "\t");
                txtAreaAvdelning.append(avdelning.get("epost") + "\t");
                txtAreaAvdelning.append(avdelning.get("telefon") + "\t");
                txtAreaAvdelning.append(avdelning.get("stad") + "\t");
                txtAreaAvdelning.append(avdelning.get("chef") + "\t");

            }
        }catch(InfException ex){
            System.out.println(ex.getMessage());

        }

    }//GEN-LAST:event_txtAreaAvdelningFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAndraMinInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblInloggadAnvandare;
    private javax.swing.JLabel lblLOGGA;
    private javax.swing.JLabel lblValkommen;
    private javax.swing.JPanel panelAnstallda;
    private javax.swing.JPanel panelAvdelning;
    private javax.swing.JPanel panelMinInfo;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JTextArea txtAreaAvdelning;
    // End of variables declaration//GEN-END:variables
}
