/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_24;

import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author marti
 */
public class andraAnstalld extends javax.swing.JFrame {
private InfDB idb;
private String ePost;
private BehorighetsKontrol behorighetsKontrol;
    /**
     * Creates new form andraAnstalld
     */
    public andraAnstalld(InfDB idb, String ePost) {
        this.idb = idb;
        this.ePost = ePost;
        this.behorighetsKontrol = new BehorighetsKontrol();
        initComponents();
        fyllFormularMedAnstalldInfo();
        //panelEdit.setVisible(false);
    
       
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFornamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblAdres = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        tfFornamn = new javax.swing.JTextField();
        tfEfternamn = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfEpost = new javax.swing.JTextField();
        tfTelefon = new javax.swing.JTextField();
        btnSpara = new javax.swing.JToggleButton();
        btnAvbryt = new javax.swing.JToggleButton();
        lblFormularAndraPersUpp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFornamn.setText("Förnamn:");

        lblEfternamn.setText("Efternamn:");

        lblTelefon.setText("Telefon:");

        lblAdres.setText("Adress:");

        lblEpost.setText("E-Post:");

        btnSpara.setBackground(new java.awt.Color(53, 128, 78));
        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnAvbryt.setBackground(new java.awt.Color(161, 50, 50));
        btnAvbryt.setText("Avbryt");
        btnAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvbrytActionPerformed(evt);
            }
        });

        lblFormularAndraPersUpp.setText("Formulär: Ändra personuppgifter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFornamn)
                    .addComponent(lblEfternamn)
                    .addComponent(lblAdres)
                    .addComponent(lblEpost)
                    .addComponent(lblTelefon))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfFornamn)
                    .addComponent(tfEfternamn)
                    .addComponent(tfAdress)
                    .addComponent(tfEpost)
                    .addComponent(tfTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFormularAndraPersUpp)
                        .addGap(39, 39, 39)))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSpara)
                .addGap(18, 18, 18)
                .addComponent(btnAvbryt)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblFormularAndraPersUpp)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornamn)
                    .addComponent(tfFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEfternamn)
                    .addComponent(tfEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdres)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvbryt)
                    .addComponent(btnSpara))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvbrytActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAvbrytActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        try {
        // Hämta uppdaterade värden från textfälten
        String nyttFornamn = tfFornamn.getText();
        String nyttEfternamn = tfEfternamn.getText();
        String nyAdress = tfAdress.getText();
        String nyEpost = tfEpost.getText();
        String nyTelefon = tfTelefon.getText();
        

        // Uppdatera databasen med de nya värdena
        String updateQuery = "UPDATE anstalld SET fornamn = '" + nyttFornamn + "', efternamn = '" + nyttEfternamn + "', adress = '" + nyAdress + "', epost = '" + nyEpost + "', telefon = '" + nyTelefon + "' WHERE anstalld.epost = '" + ePost +"'";

        idb.update(updateQuery);

        // Meddela användaren om att uppdateringen har slutförts
        JOptionPane.showMessageDialog(this, "Dina personuppgifter har uppdaterats", "Uppdatering klar", JOptionPane.INFORMATION_MESSAGE);

        // Uppdatera fönstret med den uppdaterade informationen
        fyllFormularMedAnstalldInfo();
    } catch (InfException ex) {
        // Hantera eventuella fel som kan uppstå vid uppdateringen
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Fel vid uppdatering av anstalldinformation", "Fel", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSparaActionPerformed

    public void fyllFormularMedAnstalldInfo(){
        
        try{
        String sqlProfilInfo = "SELECT * from anstalld WHERE ePost = '" + ePost + "'";
        HashMap<String,String> anstalldInfo = idb.fetchRow(sqlProfilInfo);

    if(anstalldInfo !=null){
        tfFornamn.setText(anstalldInfo.get("fornamn"));
        tfEfternamn.setText(anstalldInfo.get("efternamn"));
        tfAdress.setText(anstalldInfo.get("adress"));
        tfEpost.setText(anstalldInfo.get("epost"));
        tfTelefon.setText(anstalldInfo.get("telefon"));
        
    }
        }catch(InfException ex){
            System.out.println(ex.getMessage());

        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(andraAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(andraAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(andraAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(andraAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new andraAnstalld().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAvbryt;
    private javax.swing.JToggleButton btnSpara;
    private javax.swing.JLabel lblAdres;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFormularAndraPersUpp;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfEfternamn;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfFornamn;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}
