
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_24;

import java.awt.Component;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marti
 */
public class Handlaggare extends javax.swing.JFrame {
private InfDB idb;
private String ePost;

    /**
     * Creates new form Handlaggare
     * @param idb
     * @param ePost
     */
    public Handlaggare(InfDB idb, String ePost){
        this.idb = idb;
        this.ePost = ePost;
        initComponents();
         lblInloggadAnvandare.setText(ePost);
         
         btnAndraProjekt.setVisible(false);
         
}
         
    public Handlaggare (InfDB idb, String ePost, boolean isProjektChef){
        this.idb = idb;
        this.ePost = ePost;      
        initComponents();
        lblInloggadAnvandare.setText(ePost);
         if (isProjektChef) {
            btnAndraProjekt.setVisible(true);
        } else {
            btnAndraProjekt.setVisible(false);
            
}
    }
    
   //String ePost = lblInloggadAnvandare.getText();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValkommen = new javax.swing.JLabel();
        lblInloggadAnvandare = new javax.swing.JLabel();
        lblHandlaggare = new javax.swing.JLabel();
        lblLOGGA = new javax.swing.JLabel();
        tabby = new javax.swing.JTabbedPane();
        panelProjekt = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaProjekt = new javax.swing.JTextArea();
        btnAndraProjekt = new javax.swing.JToggleButton();
        panelAvdelning = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaAvdelning = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnAvdelningensAnstallda = new javax.swing.JToggleButton();
        panelMinInfo = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaMinInfo = new javax.swing.JTextArea();
        btnAndraMinInfo = new javax.swing.JToggleButton();
        btbAndraMinInfo2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValkommen.setText("Välkommen!");

        lblInloggadAnvandare.setText("inloggadAnvandare");

        lblHandlaggare.setText("Handläggare");

        lblLOGGA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo_24/SDG+Wheel.png"))); // NOI18N

        tabby.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbyStateChanged(evt);
            }
        });

        txtAreaProjekt.setEditable(false);
        txtAreaProjekt.setColumns(20);
        txtAreaProjekt.setRows(5);
        jScrollPane2.setViewportView(txtAreaProjekt);
        txtAreaProjekt.getAccessibleContext().setAccessibleParent(panelProjekt);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAndraProjekt.setText("Ändra projekt");
        btnAndraProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraProjektActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProjektLayout = new javax.swing.GroupLayout(panelProjekt);
        panelProjekt.setLayout(panelProjektLayout);
        panelProjektLayout.setHorizontalGroup(
            panelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjektLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProjektLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAndraProjekt)
                .addGap(26, 26, 26))
        );
        panelProjektLayout.setVerticalGroup(
            panelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProjektLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAndraProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabby.addTab("Mina projekt", panelProjekt);

        txtAreaAvdelning.setEditable(false);
        txtAreaAvdelning.setColumns(20);
        txtAreaAvdelning.setRows(5);
        jScrollPane3.setViewportView(txtAreaAvdelning);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jToggleButton1.setText("Avdelningens projekt");

        btnAvdelningensAnstallda.setText("Avdelningens anställda");

        javax.swing.GroupLayout panelAvdelningLayout = new javax.swing.GroupLayout(panelAvdelning);
        panelAvdelning.setLayout(panelAvdelningLayout);
        panelAvdelningLayout.setHorizontalGroup(
            panelAvdelningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvdelningLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAvdelningLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAvdelningensAnstallda)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );
        panelAvdelningLayout.setVerticalGroup(
            panelAvdelningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAvdelningLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAvdelningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(btnAvdelningensAnstallda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabby.addTab("Min avdelning", panelAvdelning);

        txtAreaMinInfo.setEditable(false);
        txtAreaMinInfo.setColumns(20);
        txtAreaMinInfo.setRows(5);
        jScrollPane4.setViewportView(txtAreaMinInfo);

        btnAndraMinInfo.setText("Ändra min info");
        btnAndraMinInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraMinInfoActionPerformed(evt);
            }
        });

        btbAndraMinInfo2.setText("Ändra min profil");
        btbAndraMinInfo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbAndraMinInfo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMinInfoLayout = new javax.swing.GroupLayout(panelMinInfo);
        panelMinInfo.setLayout(panelMinInfoLayout);
        panelMinInfoLayout.setHorizontalGroup(
            panelMinInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMinInfoLayout.createSequentialGroup()
                .addGroup(panelMinInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMinInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMinInfoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btbAndraMinInfo2)
                        .addGap(42, 42, 42)))
                .addComponent(btnAndraMinInfo)
                .addGap(14, 14, 14))
        );
        panelMinInfoLayout.setVerticalGroup(
            panelMinInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMinInfoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnAndraMinInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMinInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btbAndraMinInfo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        tabby.addTab("Min  profil", panelMinInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValkommen)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHandlaggare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInloggadAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLOGGA, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabby, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValkommen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInloggadAnvandare)
                            .addComponent(lblHandlaggare)))
                    .addComponent(lblLOGGA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(tabby)
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabbyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbyStateChanged
        int index = tabby.getSelectedIndex();
    switch(index) {
        case 0:
            visaProjektInformation();
            break;
        case 1:
            visaAvdelningsInformation();
            break;
        case 2:
            visaProfilInformation();
            break;
        // Lägg till fler fall för fler flikar om det behövs
    }
    }//GEN-LAST:event_tabbyStateChanged

    private void btnAndraMinInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraMinInfoActionPerformed
       //ANVÄNDS EJ KNAPPEN ÄR FÖRSVUNNEN FRÅN DESIGN!!!!!!! OBSS
    }//GEN-LAST:event_btnAndraMinInfoActionPerformed

    private void btnAndraProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraProjektActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAndraProjektActionPerformed

    private void btbAndraMinInfo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbAndraMinInfo2ActionPerformed
        new andraAnstalld (idb, ePost).setVisible(true);
        
        
    }//GEN-LAST:event_btbAndraMinInfo2ActionPerformed
public void uppdateraAnvandarensInfo(String nyttFörnamn,String nyttEfternamn,String nyAdress,String nyEpost,String nyTelefon){
    
        //String nyttFörnamn = "set"
    }
   
public void visaProjektInformation(){

try{
            txtAreaProjekt.setText("");
            ArrayList<HashMap<String,String>> allaProjekt;
            String sqlFraga = "SELECT * FROM projekt INNER JOIN anstalld ON projekt.projektchef = anstalld.AID WHERE ePost = '" + ePost + "'";

            allaProjekt = idb.fetchRows(sqlFraga);

            for(HashMap<String,String> projekt : allaProjekt){
                txtAreaProjekt.append(projekt.get("pid") + "\t");
                txtAreaProjekt.append(projekt.get("projektnamn") + "\t");
                txtAreaProjekt.append(projekt.get("beskrivning") + "\t");
                txtAreaProjekt.append(projekt.get("startdatum") + "\t");
                txtAreaProjekt.append(projekt.get("slutdatum") + "\t");
                txtAreaProjekt.append(projekt.get("kostnad") + "\t");
                txtAreaProjekt.append(projekt.get("status") + "\t");
                txtAreaProjekt.append(projekt.get("prioritet") + "\t");
                txtAreaProjekt.append(projekt.get("projektchef") + "\t");
                txtAreaProjekt.append(projekt.get("land") + "\t");
            }

        }catch(InfException ex){
            System.out.println(ex.getMessage());

        }   
}
public void visaAvdelningsInformation (){
        txtAreaAvdelning.setText("");

        ArrayList<HashMap<String,String>> allaAvdelning;

        try {
            String sqlAvdelning = "SELECT * FROM avdelning "
                    + "INNER JOIN anstalld ON avdelning.avdid = anstalld.avdelning "
                    + "WHERE anstalld.ePost = '" + ePost +"'";
            allaAvdelning = idb.fetchRows(sqlAvdelning);

            for(HashMap<String,String> avdelning : allaAvdelning ){
                txtAreaAvdelning.append(avdelning.get("avdid") + "\t");
                txtAreaAvdelning.append(avdelning.get("namn") + "\t");
                txtAreaAvdelning.append(avdelning.get("beskrivning") + "\t");
                txtAreaAvdelning.append(avdelning.get("adress") + "\t");
                txtAreaAvdelning.append(avdelning.get("epost") + "\t");
                txtAreaAvdelning.append(avdelning.get("telefon") + "\t");
                txtAreaAvdelning.append(avdelning.get("stad") + "\t");
                txtAreaAvdelning.append(avdelning.get("chef") + "\t");

            }
        }catch(InfException ex){
            System.out.println(ex.getMessage());

        }
}
public void visaProfilInformation(){
    txtAreaMinInfo.setText("");
    HashMap<String,String> anstalldInfo;

    try{
        String sqlProfilInfo = "SELECT * from anstalld WHERE ePost = '" + ePost + "'";
        anstalldInfo = idb.fetchRow(sqlProfilInfo);

    if(anstalldInfo !=null){
        txtAreaMinInfo.append(anstalldInfo.get("aid") + "\t");
        txtAreaMinInfo.append(anstalldInfo.get("fornamn") + "\t");
        txtAreaMinInfo.append(anstalldInfo.get("efternamn") + "\t");
        txtAreaMinInfo.append(anstalldInfo.get("adress") + "\t");
        txtAreaMinInfo.append(anstalldInfo.get("epost") + "\t");
        txtAreaMinInfo.append(anstalldInfo.get("telefon") + "\t");
        txtAreaMinInfo.append(anstalldInfo.get("anstallningsdatum") + "\t");
        txtAreaMinInfo.append(anstalldInfo.get("avdelning") + "\t");

}
        }catch(InfException ex){
            System.out.println(ex.getMessage());

        }
}
   
    
    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Handlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Handlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Handlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Handlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
                //new Handlaggare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btbAndraMinInfo2;
    private javax.swing.JToggleButton btnAndraMinInfo;
    private javax.swing.JToggleButton btnAndraProjekt;
    private javax.swing.JToggleButton btnAvdelningensAnstallda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblHandlaggare;
    private javax.swing.JLabel lblInloggadAnvandare;
    private javax.swing.JLabel lblLOGGA;
    private javax.swing.JLabel lblValkommen;
    private javax.swing.JPanel panelAvdelning;
    private javax.swing.JPanel panelMinInfo;
    private javax.swing.JPanel panelProjekt;
    private javax.swing.JTabbedPane tabby;
    private javax.swing.JTextArea txtAreaAvdelning;
    private javax.swing.JTextArea txtAreaMinInfo;
    private javax.swing.JTextArea txtAreaProjekt;
    // End of variables declaration//GEN-END:variables
}
