/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_24;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author marti
 */
public class Meny extends javax.swing.JFrame {
    
  private InfDB idb;
  private String inloggadAnvandare;
    private DefaultTableModel projTab;
    /**
     * Creates new form Meny
     * @param idb
     */
    public Meny(InfDB idb,String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        lblInloggadAnvandare.setText(inloggadAnvandare);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInloggadAnvandare = new javax.swing.JLabel();
        lblValkommen = new javax.swing.JLabel();
        btnProjekt = new javax.swing.JToggleButton();
        btnAnstalldInfo = new javax.swing.JToggleButton();
        btnAvdelning = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.lightGray);

        lblValkommen.setText("Väkommen!");

        btnProjekt.setText("Projekt");
        btnProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjektActionPerformed(evt);
            }
        });

        btnAnstalldInfo.setText("Anstalldinfo");

        btnAvdelning.setText("Avdelning");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblValkommen))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblInloggadAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnAnstalldInfo)
                .addGap(28, 28, 28)
                .addComponent(btnProjekt)
                .addGap(27, 27, 27)
                .addComponent(btnAvdelning))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblValkommen)
                .addGap(6, 6, 6)
                .addComponent(lblInloggadAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnstalldInfo)
                    .addComponent(btnProjekt)
                    .addComponent(btnAvdelning)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektActionPerformed
             String ePost = lblInloggadAnvandare.getText();
            
    String sqlFraga1 = "SELECT aid FROM anstalld WHERE epost = '" + ePost + "'";
    String sqlFraga2 = "SELECT projekt.* FROM projekt INNER JOIN ans_proj ON projekt.PID = ans_proj.PID INNER JOIN anstalld ON ans_proj.AID = anstalld.AID WHERE anstalld.AID = '" + ePost + "'";
    System.out.println(sqlFraga1 + sqlFraga2);

    try {
        ArrayList<String> dbProjekt = idb.fetchColumn(sqlFraga2);
        //String dbProjekt = idb.fetchSingle(sqlFraga2);
        if (dbProjekt != null) { // Kontrollera om ett projekt har hämtats från databasen
           new ProjektNy(idb, ePost, projTab).setVisible(true); // Skapa och visa Projekt-fönstret
        } else {
            System.out.println("Inga projekt hittades för användaren."); // Meddelande om inga projekt hittades
        }
    } catch (InfException ex) {
        Logger.getLogger(Meny.class.getName()).log(Level.SEVERE, null, ex);
    }          
   
    }//GEN-LAST:event_btnProjektActionPerformed

    /**
     * /@param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Meny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAnstalldInfo;
    private javax.swing.JToggleButton btnAvdelning;
    private javax.swing.JToggleButton btnProjekt;
    private javax.swing.JLabel lblInloggadAnvandare;
    private javax.swing.JLabel lblValkommen;
    // End of variables declaration//GEN-END:variables
}