/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_24;

import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author marti
 */
public class Meny extends javax.swing.JFrame {
    
  private InfDB idb;
  private String inloggadAnvandare;
    /**
     * Creates new form Meny
     */
    public Meny(InfDB idb,String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        lblInloggadAnvandare.setText(inloggadAnvandare);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInloggadAnvandare = new javax.swing.JLabel();
        lblValkommen = new javax.swing.JLabel();
        btnProjekt = new javax.swing.JToggleButton();
        btnAnstalldInfo = new javax.swing.JToggleButton();
        btnAvdelning = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.lightGray);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblInloggadAnvandare, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 55, 179, 23));

        lblValkommen.setText("Väkommen!");
        getContentPane().add(lblValkommen, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 33, -1, -1));

        btnProjekt.setText("Projekt");
        btnProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjektActionPerformed(evt);
            }
        });
        getContentPane().add(btnProjekt, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 110, -1, -1));

        btnAnstalldInfo.setText("Anstalldinfo");
        getContentPane().add(btnAnstalldInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 110, -1, -1));

        btnAvdelning.setText("Avdelning");
        getContentPane().add(btnAvdelning, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektActionPerformed
             String ePost = lblInloggadAnvandare.getText();
            
    String sqlFraga1 = "SELECT aid FROM anstalld WHERE epost = '" + ePost + "'";
    String sqlFraga2 = "SELECT pid FROM ans_proj WHERE aid = pid";
    System.out.println(sqlFraga1 + sqlFraga2);
    try {
        String dbProjekt = idb.fetchSingle(sqlFraga2);
        if (dbProjekt != null) { // Kontrollera om ett projekt har hämtats från databasen
            new Projekt(idb, ePost).setVisible(true); // Skapa och visa Projekt-fönstret
        } else {
            System.out.println("Inga projekt hittades för användaren."); // Meddelande om inga projekt hittades
        }
    } catch (InfException ex) {
        Logger.getLogger(Meny.class.getName()).log(Level.SEVERE, null, ex);
    }          
   
    }//GEN-LAST:event_btnProjektActionPerformed

    /**
     * /@param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Meny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAnstalldInfo;
    private javax.swing.JToggleButton btnAvdelning;
    private javax.swing.JToggleButton btnProjekt;
    private javax.swing.JLabel lblInloggadAnvandare;
    private javax.swing.JLabel lblValkommen;
    // End of variables declaration//GEN-END:variables
}
